cellular: cellular.cpp
	g++ -o cellular0 cellular.cpp -O0 -std=c++11
	g++ -o cellular1 cellular.cpp -O1 -std=c++11
	g++ -o cellular2 cellular.cpp -O2 -std=c++11
	g++ -o cellular3 cellular.cpp -O3 -std=c++11